name: Submit jobs

on:
  issue_comment:
    types: [created, edited]

jobs:
  show-git-hash:
    name: show git hash
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/show') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get master commit hash
        id: get-master-commit-hash
        run: echo ::set-output name=git-hash::${{ github.sha }}

      - id: fetch
        uses: actions/github-script@v5
        with:
          result-encoding: string
          script: |
            let {data: pr} = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return pr.head.sha;

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.fetch.outputs.result }}

      - name: Comment by action
        uses: actions/github-script@v5
        with:
          script: |
            const commentBody = "PR (${{ steps.fetch.outputs.result }})\n master (${{ steps.get-master-commit-hash.outputs.git-hash }})"

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })
