name: Submit jobs

on:
  issue_comment:
    types: [created, edited]

jobs:
  show-git-hash:
    name: show git hash
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/show') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get master commit hash
        id: get-master-commit-hash
        run: echo ::set-output name=git-hash::${{ github.sha }}

      - name: get upstream branch
        id: get-upstream-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=git-hash::$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.issue.pull_request.url }} | jq '.head.sha' | sed 's/\"//g')"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.get-upstream-branch.outputs.git-hash }}

      - name: Comment by action
        uses: actions/github-script@v5
        with:
          script: |
            const commentBody = "PR (${{ steps.get-upstream-branch.outputs.git-hash }}) ${{ steps.get-upstream-branch.outputs.branch-name }} \n master (${{ steps.get-master-commit-hash.outputs.git-hash }})"

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: commentBody
            })
